dev-ostelco-ios-clientTests/MyInfoTests.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Models/MyInfoDetails+Testing.swift
ostelco-ios-client/Models/MyInfoDetails.swift
ostelco-ios-client/Network/APIManager.swift
ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift

We were using `SwiftyJSON` essentially for one piece of parsing - I've updated this to use `Codable` parsing instead, and added a test against some test data we were already using.
Note: Actually removing the framework will come in another PR, wanted to separate Pod changes from code changes here.

Remove Swifty JSON in favor of Codable parsing

---

ostelco-ios-client.xcodeproj/project.pbxproj

Looks like `MyInfoDetails` somehow got removed from the `ostelco-ios-client` target, which prevented a build.

Fix production target

---

ostelco-ios-client/Extensions/UIViewController+ActionSheet.swift
ostelco-ios-client/Extensions/UIViewController+StartApplePay.swift
ostelco-ios-client/Models/Product.swift
ostelco-ios-client/ViewControllers/Home/BecomeAMemberViewController.swift
ostelco-ios-client/ViewControllers/Home/HomeViewController2.swift

Prime expects amount in currency’s smallest unit. For example, to
charge $10 USD, use an amount value of 1000 (i.e, 1000 cents).

Use the correct denomination while doing apple pay.

---

ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift

also handle pending case by checking kycStatusMap since region status will be pending even if the jumio flow has failed

fix rejected case to be triggered if any is rejected instead of all

---

ostelco-ios-client/Storyboards/Login.storyboard

@havard024 found a bug where if you've got an Xr that's set up to used a zoomed display, text will get cut off from the labels in the onboarding panels. 
In this PR I've futzed around with autolayout constraints until I got something that looks reasonably good on an iPhone 6 sim (which is about the same size as the zoomed iPhone Xr screen - zoomed mode is not something you can test on sim, unfortunately) but still looks good on unzoomed larger phones.

Better support for zoomed screens on login onboarding

---

ostelco-ios-client/Models/SimProfile.swift
ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift

A recent change in Prime has made the eSimActivationCode a nullable field.
This is a temporary fix for the crash we are getting while parsing the context

Fix for empty eSimActivationCode

---

ostelco-ios-client/ViewControllers/Country/LocationProblemViewController.swift

This adds handling for returning from the background after enabling location services at the system rather than app level. This also improves handling if the user declines location services for our app once they've enabled them at the system level. 
One unfortunate note: There's no way to kick the user to the root of settings rather than the root of our app's settings without using private API - we may need to consider a slight adjustment to the illustration because of this, since it adds an extra step. cc @oisinzimmermann

Better handling for system-wide location disabling

---

dev-ostelco-ios-clientTests/MyInfoTests.swift
ostelco-core/Models/MyInfoDetails.swift
ostelco-core/Network/APIEndpoint.swift
ostelco-core/Network/LoggedInAPI.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Models/MyInfoDetails+Testing.swift
ostelco-ios-client/Models/Product.swift
ostelco-ios-client/Network/APIManager.swift
ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift
ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift
ostelco-ios-client/ViewControllers/Home/ApplePayViewController.swift
ostelco-ios-client/ViewControllers/Home/BecomeAMemberViewController.swift
ostelco-ios-client/ViewControllers/Home/HomeViewController.swift
ostelco-ios-client/ViewControllers/Home/PurchaseHistoryTableViewController.swift

In this PR: 
- Migrated most things using `load()` for `GET` API calls from Siesta to `LoggedInAPI`, which is using promise wrappers and handling data parsing under the hood.
- Removed no-longer-needed transformers from `APIManager`
- Moved `MyInfoDetails` to core. 
- Removed deprecated `Product` initializer and gave it a debugDescription
Future PRs (ie, things NOT done in this PR): 
- Update base pipeline based on final auth decision. **NOTE: This means auto-refreshing of tokens won't work on the migrated calls until that's done.** 
- Migrate the `context` calls using `load()` - right now that whole thing is a rat's nest in two different places, and I wanted to try and focus on some more low-hanging fruit first.
- Migrate stuff using `request` (most of which requires a bit more work).

Migrate more calls to LoggedInAPI

---

dev-ostelco-ios-clientTests/RequestGeneratorTests.swift
ostelco-core/Network/Request.swift
ostelco-ios-client/ViewControllers/Home/HomeViewController.swift

In this PR: 
- Added and tested ability to have `URLQueryItem`s on a `Request`.
- Resolved whitespace warning from SwiftLint.

Add ability to have query parameters on a `Request`

---

ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Extensions/UIAlertAction+Convenience.swift
ostelco-ios-client/Extensions/UIViewController+ActionSheet.swift
ostelco-ios-client/Extensions/UIViewController+Alerts.swift
ostelco-ios-client/Protocols/LocationCheckingViewController.swift
ostelco-ios-client/ViewControllers/EKYC/AddressEditViewController.swift
ostelco-ios-client/ViewControllers/EKYC/NRCIVerifyViewController.swift
ostelco-ios-client/ViewControllers/Home/BecomeAMemberViewController.swift
ostelco-ios-client/ViewControllers/Home/HomeViewController.swift

In this PR: 
- Add some handling so if we get information from the server or a `LocalizedError` about what's gone wrong, we show that instead of a really goofy error alert
- Add some convenience helpers for generating common button types
- Use convenience APIs where appropriate.

Improve error messaging

---

fastlane/Fastfile

We no longer store the GoogleService-Info-dev.plist in the repo. This can be downloaded from firebase dashboard. Only required if you upload the symbols to firebase

Update fastlane script

---

dev-ostelco-ios-clientTests/APITests/LiveAPITests.swift
dev-ostelco-ios-clientTests/APITests/MockAPITests.swift
dev-ostelco-ios-clientTests/MockJSON/my_info_config.json
dev-ostelco-ios-clientTests/MockJSON/products.json
dev-ostelco-ios-clientTests/MockJSON/region_singapore.json
dev-ostelco-ios-clientTests/MockJSON/region_vanuatu.json
dev-ostelco-ios-clientTests/MockJSON/regions.json
dev-ostelco-ios-clientTests/MockJSON/regions_multiple.json
dev-ostelco-ios-clientTests/MockJSON/sim_profiles_singapore.json
dev-ostelco-ios-clientTests/MockJSON/stripe_ephemeral_key.json
dev-ostelco-ios-clientTests/MyInfoTests.swift
dev-ostelco-ios-clientTests/XCTestCase+MockingHelpers.swift
ostelco-core/Extensions/Array+FancyAppend.swift
ostelco-core/Extensions/URLQueryItem+Codable.swift
ostelco-core/Models/EKYCAddress.swift
ostelco-core/Models/EKYCProfileUpdate.swift
ostelco-core/Models/MyInfoDetails.swift
ostelco-core/Models/PaymentInfo.swift
ostelco-core/Models/SimProfileRequest.swift
ostelco-core/Models/StripeEphemeralKeyRequest.swift
ostelco-core/Models/UserSetup.swift
ostelco-core/Network/APIHelper.swift
ostelco-core/Network/PrimeAPI.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Models/MyInfoDetails+Testing.swift
ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
ostelco-ios-client/ViewControllers/Home/ApplePayViewController.swift

In this PR: 
- Added a whole mess more mock + live API tests (again, live API tests don't run on the server, and won't run locally unless you have a logged in user).
- Updated Stripe ephemeral token API to return a non optional `[String: AnyHashable]` (which is what auto-converts to `NSDictionary` nowadays)
- Moved some formatting stuff to `MyInfoAddress` and added tests around it
- Updated `Codable` things that are being sent as query params to have `asQueryParams` properties so that's all still under the hood of the object

Even more API tests!

---

Gemfile
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

In this PR:
- Bumped Fastlane to latest version
- Added a way for Fastlane to call the SPM script. This allows us to keep the `secrets` JSON files as the single source of truth for what needs to go into the `GoogleServices-Info.plist`.

Add lane for Fastlane to call the SPM script so dysms can be properly uploaded

---

ostelco-ios-client/Coordinators/RootCoordinator.swift
ostelco-ios-client/Extensions/UNAuthorizationStatusExtensions.swift
ostelco-ios-client/ModelControllers/AddressEditDataSource.swift
ostelco-ios-client/Network/AppErrors.swift
ostelco-ios-client/Protocols/ApplePayDelegate.swift
ostelco-ios-client/Protocols/LocationCheckingViewController.swift
ostelco-ios-client/SupportingFiles/Environment.swift
ostelco-ios-client/ViewControllers/Country/AllowLocationAccessViewController.swift
ostelco-ios-client/ViewControllers/Country/LocationProblemViewController.swift
ostelco-ios-client/ViewControllers/EKYC/AddressEditViewController.swift
ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
ostelco-ios-client/ViewControllers/EKYC/SelectIdentityVerificationMethodViewController.swift
ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift
ostelco-ios-client/ViewControllers/Email/CheckEmailViewController.swift
ostelco-ios-client/ViewControllers/Email/EmailEntryViewController.swift
ostelco-ios-client/ViewControllers/Home/ApplePayViewController.swift
ostelco-ios-client/ViewControllers/Home/HomeViewController.swift
ostelco-ios-client/ViewControllers/OhNoViewController.swift
ostelco-ios-client/ViewControllers/SignUp/GetStartedViewController.swift

Went through and audited what we're sending to Crashlytics and made sure that: 
- All errors coming through the API or other `catch` blocks in PromiseKit that are not explicitly handled get logged
- We now have an `ApplicationErrors.assertAndLog` method that allows you to have an assertion failure at the point where `assertAndLog` is called during dev, and to send an error to crashlytics in production

Send more errors to Crashlytics

---

OstelcoStyles/OstelcoButton.swift
ostelco-ios-client/Storyboards/Country.storyboard
ostelco-ios-client/Storyboards/EKYC.storyboard
ostelco-ios-client/Storyboards/ESim.storyboard
ostelco-ios-client/Storyboards/Login.storyboard

This PR updates the button styling of the `PrimaryButton` and `SmallButton` to use the same style of drop shadow as the `BuyButton`.
Bunch of IB changes in here come from going through and making sure everything displays correctly in Interface Builder:

Update button styling

---

OstelcoStyles/OstelcoButton.swift
ostelco-ios-client/Storyboards/OhNo.storyboard

This PR fixes an issue where a rounded button's background was not properly adjusting size when a view was re-laid out, which made `PrimaryButton` in particular look lopsided on an iPhone XS Max. (Good catch @prasanthu)

Fix Button stretchiness

---

OstelcoStyles/OstelcoButton.swift
ostelco-ios-client/Storyboards/EKYC.storyboard
ostelco-ios-client/Storyboards/SignUp.storyboard
ostelco-ios-client/ViewControllers/EKYC/SelectIdentityVerificationMethodViewController.swift
ostelco-ios-client/ViewControllers/SignUp/TheLegalStuffViewController.swift

In this PR: 
- Update look of checkmark to match updated designs
- Add age check to legal stuff screen
- Add Radio buttons per updated designs
- Add drop-shadow buttons to go with radio buttons
- Use radio buttons + drop shadow  buttons  in the choose-your-own-EKYC-adventure view controller

Checkmarks + Radio Buttons + Drop Shadow Buttons

---

OstelcoStyles/LinkableText.swift
OstelcoStyles/OstelcoLabel.swift
Pods/Pods.xcodeproj/project.pbxproj
dev-ostelco-ios-clientTests/APITests/LinkableTextTests.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Storyboards/Home.storyboard
ostelco-ios-client/ViewControllers/Home/HomeViewController.swift
ostelco-ios-client/ViewControllers/Login/OnboardingPageViewController.swift

In this PR: 
- Added and tested a data structure around having an amount of full text with an arbitrary number of links contained within
- Added support for using that data structure to set up links within an `OstelcoLabel`
- Consolidated support for setting up attributed strings within a larger string for both bolding and links
- Used that consolidation to considerably simplify the logic for the `DataAmountOnHomeLabel` (which will come in handy for the Today widget)
- Added handling of tapping on `OstelcoLabels`
- Set all this up for realsies in the login carousel
Next PR: 
- Implement links in the rest of the app.

Linky Labels!

---

dev-ostelco-ios-clientTests/APITests/LiveAPITests.swift
ostelco-ios-client/AppDelegate.swift
ostelco-ios-client/ModelControllers/PushNotificationController.swift

Was hoping to have more of this working, but it's probably worth merging what's in here so far since it'll make debugging all this crap a lot easier if we do another build while I'm at UIKonf.
In this PR: 
- Move all handling of FreshChat push notifications to the `PushNotificationController`. 
- Removed one check from the live tests that could fail for legit reasons.

Move Freshchat push stuff to the push notification controller

---

OstelcoStyles/BoldableText.swift
OstelcoStyles/OstelcoLabel.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/AppDelegate.swift
ostelco-ios-client/Coordinators/RootCoordinator.swift
ostelco-ios-client/Network/InternetConnectionMonitor.swift
ostelco-ios-client/Storyboards/OhNo.storyboard
ostelco-ios-client/ViewControllers/ESim/ESIMPageViewController.swift
ostelco-ios-client/ViewControllers/OhNoViewController.swift

In this PR: 
- Added an Internet Connection Monitor that uses `NWPathMonitor` under the hood. This is a new class in iOS 12, and it's got some weirdness going on about it with the simulator, but otherwise works well. 
- Updated the `OhNo` view controller to handle showing the no internet connection screen
- Moved `BoldableText` into `OstelcoStyles` for easier future use.

Add Internet Connection Monitor

---

dev-ostelco-ios-clientTests/APITests/MockAPITests.swift
dev-ostelco-ios-clientTests/MockJSON/push_notification_scan_success.json
dev-ostelco-ios-clientTests/PushParsingTests.swift
dev-ostelco-ios-clientTests/RegionResponseTests.swift
ostelco-core/Models/EKYCStatus.swift
ostelco-core/Models/JumioScanInfo.swift
ostelco-core/Models/PushNotificationModel.swift
ostelco-core/Models/Region.swift
ostelco-core/Models/Scan.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/Protocols/PushNotificationHandling.swift
ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift
ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift

In this PR: 
- Add and test handling of receiving of actual push notifications
- Handle associated data coming in from notification
- Add a whole mess of stuff around Jumio error types based on their docs
- Remove handling of push around ESim since we're not actually sending pushes about this. 
NOT in this PR: 
- Actual handling of those Jumio errors (this is a separate ticket)

Handle push around Jumio approval/Rejection

---

ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/AppDelegate.swift
ostelco-ios-client/Network/LinkHelper.swift
ostelco-ios-client/Network/UsernameAndPasswordLinkManager.swift

Allows username and password login using deep link.
You can only use this deep link to share credentials to existing users.
To share credentials of existing user:
1. Set a password for an existing user by resetting the password for an existing user in firebase console
2. Construct the deep link https://dl-dev.oya.world/login-with-username-and-password?username=[email]&password=[password]
3. Make sure the app is already closed to prevent routing logic issues
4. enter the url from 2 to a browser on the phone
5. then manually open the app from the status bar in the browser if the app doesn't open automatically

add deep link to allow login with username and password

---

.circleci/config.yml

To merge PR into develop, we require CI to pass, CI only builds braches with certain prefixes, refactor prefix is now one of those.

Allow refactor branches to be built in CI.

---

ostelco-ios-client/Coordinators/SignUpCoordinator.swift
ostelco-ios-client/ViewControllers/SignUp/EnableNotificationsViewController.swift
ostelco-ios-client/ViewControllers/SignUp/GetStartedViewController.swift
ostelco-ios-client/ViewControllers/SignUp/TheLegalStuffViewController.swift

This cuts their tie with specific coordinators and allows them to be
used anywhere.

Move some more controllers to use delegates.

---

scripts/SPM/Package.swift

Lock SPM minor version since I experienced issues building the project with SPM version 0.4.0.
scripts/SPM/swift build
'SPM' /Users/mac/github/xcode/ostelco-ios-client/scripts/SPM: error: product dependency 'Utility' not found
warning: dependency 'SwiftPM' is not used by any target

Lock SPM minor version.

---

Gemfile
Gemfile.lock

This still won't fix CVE-2019-13574. The fix is coming in next
version, see the PR here:
https://github.com/fastlane/fastlane/pull/15042

Update fastlane to latest version.

---

ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift

Dumber view controllers are much easier to manage. This fixes the issue
where a cold-start in the eSim section would crash the app.

Move API calls from pending download.

---

ostelco-ios-client.xcodeproj/project.pbxproj

Forgot to enable this before. We now have 0 warnings and we want to keep
it this way, so warnings are now errors.

Warnings are now errors.

---

dev-ostelco-ios-clientTests/CoordinatorTests/EdgeCasesInStageDeciderTests.swift
dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithSingPassStageDeciderTests.swift
ostelco-core/ModelControllers/UserDefaultsWrapper.swift
ostelco-core/Models/StageDecider.swift
ostelco-ios-client.xcodeproj/project.pbxproj
ostelco-ios-client/AppDelegate.swift
ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
ostelco-ios-client/Network/EmailLinkManager.swift

This way should result in less confusion about which email to use. The
coordinator always uses the email from the local context.

Fix how the pending email is handled.

---

dev-ostelco-ios-clientTests/LocalContextTests.swift
ostelco-core/Models/StageDecider.swift
ostelco-ios-client/Coordinators/OnboardingCoordinator.swift

Since they myinfo code is only good for one use, this let's that show in
the code. Once the code is accessed, it will be cleared out. This should
help to make sure we don't forget to clean up anywhere and cause
behavioral errors.

Fix issues with using the one-time code too much.

---

ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
ostelco-ios-client/ViewControllers/ESim/ESIMInstructionsViewController.swift

If you get through the onboarding and hit continue after seeing the eSim
instructions multiple times, you can get multiple sims. This prevents
that by making the button un-tappable after you tap it once.

Prevent multiple eSim profile creation.

---

ostelco-ios-client/Storyboards/Base.lproj/Settings.storyboard
ostelco-ios-client/ViewControllers/Home/SettingsTableViewController.swift

This isn't implemented, so the fastest solution is to eliminate it. We
agreed to do this at our last iOS planning meeting.

Remove the change nickname option.

---

scripts/SPM/Sources/SPM/main.swift

.none is ambiguous because Optional has none but also ShellCompletion
has none. Using nil here makes it clear to the compiler.

Fix warnings from Xcode Beta 6

---

ostelco-ios-client/Storyboards/Base.lproj/EKYC.storyboard
ostelco-ios-client/Storyboards/Base.lproj/ESim.storyboard

Align the Controls in  Select Verification method screen.
1) Fix for https://trello.com/c/ITxioYp9/256-layout-of-ekyc-options-in-verify-you-identity-screen-is-right-aligned-when-it-should-be-centred
2) Fix for https://trello.com/c/dwBfY58D/260-typo-in-esim-instructions-video-card-allright-should-be-alright

Align the controls to center.

---

dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithScanICStageDeciderTests.swift
ostelco-core/Models/StageDecider.swift
ostelco-ios-client/ViewControllers/Login/LoginViewController.swift

Singapore people no longer need the nric screens. They're not mandatory
in the server and we don't need to waste user time with it.

Remove NRIC

---

dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithScanICStageDeciderTests.swift
ostelco-core/Models/StageDecider.swift

If the user has started Jumio and it is pending, we don't want them to
restart Jumio again, just wait until it's done.

Handle the case where user already started Jumio
