ostelco/ostelco-ios-client

- README.md
> Add details about deployment.

- README.md
- ostelco-ios-client/Assets.xcassets/White.colorset/Contents.json
- ostelco-ios-client/Auth.swift
- ostelco-ios-client/Auth0.plist
- ostelco-ios-client/Base.lproj/Main.storyboard
- ostelco-ios-client/Development.plist
- ostelco-ios-client/Development.xcconfig
- ostelco-ios-client/Environment.swift
- ostelco-ios-client/LoginViewController.swift
- ostelco-ios-client/OstelcoAPI.swift
- ostelco-ios-client/Production.plist
- ostelco-ios-client/Production.xcconfig
- ostelco-ios-client/ThemeManager.swift
- ostelco-ios-client/UIHelpers.swift
move login button style from storyboard to VC
add support for different auth0 client for dev and prod
> change from google  to passwordless login

- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/src/features/login/Login.storyboard
- ostelco-ios-client/src/features/login/LoginViewController2.swift
- ostelco-ios-client/src/features/sign-up/GetStartedViewController.swift
- ostelco-ios-client/src/features/splash/SplashViewController.swift
- ostelco-ios-client/src/models/Context.swift
- ostelco-ios-client/src/services/APIManager.swift
- ostelco-ios-client/src/services/Auth.swift
Update POST customer API to use query params instead of body
Force auth0 login prompt if user clicks logout
> Use context instead of customer API on splash and login screen

- dev-ostelco-ios-clientTests/Info.plist
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/SupportingFiles/Development.plist
- ostelco-ios-client/SupportingFiles/Production.plist
I forgot to merge a release branch for the latest build to testflight, so manually bumping the build number to match the one currently in testflight
> Version Bump

- dev-ostelco-ios-clientTests/EnumHelperTests.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/dev-ostelco-ios-client.xcscheme
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/ostelco-ios-client.xcscheme
A stab at doing #136 a bit simpler.
Before: 
After:
> Update Product Name to be user-friendlier

- ostelco-core/Models/ProductModel.swift
- ostelco-ios-client/Network/APIManager.swift
- ostelco-ios-client/SupportingFiles/ostelco-ios-client.entitlements
- ostelco-ios-client/ViewControllers/Home/HomeViewController2.swift
- Created new cfkts for Stripe. Its stored in our stripe account
> Add new merchant Id for production app.

- dev-ostelco-ios-clientTests/HeaderGeneratorTests.swift
- dev-ostelco-ios-clientTests/KeychainTests.swift
- dev-ostelco-ios-clientTests/Mocks/MockSecureStorage.swift
- ostelco-core/Network/Headers.swift
- ostelco-core/Network/LoggedInAPI.swift
- ostelco-core/Protocols/SecureStorage.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
In anticipation of removing the current Siesta stuff, here's a basic header generator we can use a bit more flexibly than what we've presently got.
> Add and test header generator

- ostelco-core/Models/Context.swift
- ostelco-core/Models/CustomerModel.swift
- ostelco-core/Models/UserSetup.swift
- ostelco-core/Network/LoggedInAPI.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/Extensions/UIViewController+ActionSheet.swift
- ostelco-ios-client/Network/APIManager.swift
- ostelco-ios-client/Network/UserManager.swift
- ostelco-ios-client/ViewControllers/Login/LoginViewController.swift
- ostelco-ios-client/ViewControllers/SignUp/GetStartedViewController.swift
- ostelco-ios-client/ViewControllers/SplashViewController.swift
As I was working on the firebase branch I realized there were a whole mess of things I was changing that had nothing to do with firebase. So I changed those here instead. 🙃
In this PR: 
- Update customer creation/deletion to use new API
- Update Context fetching to use new API
- At least partially detangle logic in login and splash view controllers
- Add a lazy ref to the keychain for future use.
> More API movement

- ostelco-core/Network/PrimeAPI.swift
- ostelco-ios-client/ViewControllers/Home/BecomeAMemberViewController.swift
Most of our create APIs require parameters to be passed via Query
parameters.
> Fix the "Create" APIs

- ostelco-ios-client/Network/UserManager.swift
The 404 status coide is inside the requestError
> Use jsonError while loading Context

- ostelco-ios-client/ViewControllers/Country/CountriesTableViewController.swift
Good catch from @havard024 that I accidentally duplicated this call.
> Fix duplicate analytics call

- dev-ostelco-ios-clientTests/MockJSON/push_notification.json
- dev-ostelco-ios-clientTests/PushParsingTests.swift
- ostelco-core/Models/PushNotificationModel.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/ModelControllers/PushNotificationController.swift
- ostelco-ios-client/Network/AppErrors.swift
- ostelco-ios-client/Protocols/PushNotificationHandling.swift
- ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift
- ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift
In this PR: 
- Parsing push based on what we're getting from various push sources
- Fix (I THINK) issue with real push token getting set on Mock push controller.
Next PR: 
- Actual handling of data coming from Firebase
> Push Notification Parsing

- dev-ostelco-ios-clientTests/LinkableTextTests.swift
- dev-ostelco-ios-clientTests/LocationProblem+Testing.swift
- ostelco-core/Models/LocationProblem.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/Models/ExternalLink.swift
- ostelco-ios-client/Models/LocationProblem+UserFacingCopy.swift
- ostelco-ios-client/Storyboards/Country.storyboard
- ostelco-ios-client/Storyboards/Home.storyboard
- ostelco-ios-client/Storyboards/SignUp.storyboard
- ostelco-ios-client/ViewControllers/Country/AllowLocationAccessViewController.swift
- ostelco-ios-client/ViewControllers/Country/ChooseCountryViewController.swift
- ostelco-ios-client/ViewControllers/Country/LocationProblemViewController.swift
- ostelco-ios-client/ViewControllers/Home/BecomeAMemberViewController.swift
- ostelco-ios-client/ViewControllers/Login/OnboardingPageViewController.swift
- ostelco-ios-client/ViewControllers/SignUp/TheLegalStuffViewController.swift
In this PR: 
- Use linky labels where possible in currently built app
- Add tests to make sure all current linky labels are properly instantiating
- Consolidated external links so we only have one giant warning
> Use Linky Labels

- ostelco-ios-client/Storyboards/Country.storyboard
- ostelco-ios-client/Storyboards/EKYC.storyboard
- ostelco-ios-client/Storyboards/ESim.storyboard
- ostelco-ios-client/Storyboards/SignUp.storyboard
In this PR: 
- Confirmed introductory offer will be 1GB instead of 2
- Updated copy throughout to reflect this change.
> Update amount of free data

- ostelco-core/Network/APIEndpoint.swift
- ostelco-core/Network/PrimeAPI.swift
- ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift
- Added new endpoint to resend QR code by email for given sim profile in selected region.
- Updated ESIMPendingDownloadViewController to call the above API when send again button is tapped
> add logic to resend QR code by email

- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/AppDelegate.swift
- ostelco-ios-client/Extensions/UIWindow+ShakeToOpenHelp.swift
The existing code did trigger when you shook the phone.
> fix shake to open help menu

- ostelco-ios-client/Storyboards/EKYC.storyboard
Took out the extra back button on the NRIC steps view controller
> Remove extra back button

- dev-ostelco-ios-clientTests/APITests/MockAPITests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/DefaultEKYCCoordinatorTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeEKYCCoordinatorTests.swift
- dev-ostelco-ios-clientTests/Mocks/CoordinatorDestinations+Equatable.swift
- docs/singapore_ekyc_grid.md
- ostelco-core/Models/EKYCStatus.swift
- ostelco-core/Models/SimProfileRequest.swift
- ostelco-ios-client/Coordinators/EKYC/DefaultEKYCCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/EKYCCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/JumioCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/SingPassCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/SingaporeEKYCCoordinator.swift
- ostelco-ios-client/Coordinators/RootCoordinator.swift
- ostelco-ios-client/ModelControllers/UserDefaultsWrapper.swift
- ostelco-ios-client/ModelControllers/UserManager.swift
- ostelco-ios-client/Storyboards/EKYC.storyboard
- ostelco-ios-client/ViewControllers/EKYC/AddressEditViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift
- ostelco-ios-client/ViewControllers/ReusableAlerts/LogOutActionSheet.swift
- ostelco-ios-client/ViewControllers/ReusableAlerts/NeedHelpActionSheet.swift
In this PR: 
- Updated EKYC to match what I *think* are the updated cases for singapore
- Simplified things as much as I could by breaking into flows
- Added a markdown table where I'm starting to break down all the different cases. Spoiler: There are A LOT.
> Singapore EKYC is Hard. 

- dev-ostelco-ios-clientTests/APITests/MockAPITests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/CountryCoordinatorTests.swift
- dev-ostelco-ios-clientTests/MockJSON/my_info.json
- dev-ostelco-ios-clientTests/MockJSON/my_info_config.json
- dev-ostelco-ios-clientTests/Mocks/MockLocationController.swift
- dev-ostelco-ios-clientTests/Mocks/MockPlacemarks.swift
- dev-ostelco-ios-clientTests/MyInfoDetails+Testing.swift
- ostelco-core/ModelControllers/LocationController.swift
- ostelco-core/Models/MyInfoDetails.swift
- ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
This slightly duplicates #245, but this should get us to where we need to be for SingPass and US EKYC debugging.
> Enable US during debugging, update parameter name for MyInfo

- dev-ostelco-ios-clientTests/CoordinatorTests/EdgeCasesInStageDeciderTests.swift
- ostelco-core/Models/OhNoIssueType.swift
- ostelco-core/Models/StageDecider.swift
- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/ViewControllers/Home/ApplePayViewController.swift
- ostelco-ios-client/ViewControllers/OhNoViewController.swift
- Moved IssueType from OhNoViewController to own file in core as OhNoIssueType so that we can access it in the StageDecider inside core.
- Added tests for unhappy flow for both Singapore and Norway.
> Add tests for unhappy flow for Singapore and Norway.

- ostelco-ios-client/Coordinators/ESimCoordinator.swift
- ostelco-ios-client/ViewControllers/ESim/ESIMInstructionsViewController.swift
- ostelco-ios-client/ViewControllers/ESim/ESIMOnBoardingViewController.swift
- ostelco-ios-client/ViewControllers/ESim/ESIMPendingDownloadViewController.swift
- ostelco-ios-client/ViewControllers/ESim/SignUpCompletedViewController.swift
Rather than directly speak to a coordinator, I adjusted the controllers
to instead use a delegate protocol. This will free us up to move these
controllers around to other coordinators.
> Changed the eSIM flow controllers to use delegates.

- ostelco-ios-client/Coordinators/EKYC/DefaultEKYCCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/EKYCCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/SingaporeEKYCCoordinator.swift
- ostelco-ios-client/ViewControllers/EKYC/AddressEditViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/NRICVerifyViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/PendingVerificationViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/ScanICStepsViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/SelectIdentityVerificationMethodViewController.swift
- ostelco-ios-client/ViewControllers/EKYC/VerifyIdentityOnBoardingViewController.swift
Now they use a delegate protocol instead of depending on the coordinator
directly. This frees up the controllers to be used with any coordinator.
> Refactor SingaporeEKYCCoordinator's controllers.

- ostelco-core/Network/PrimeAPI.swift
- ostelco-ios-client/Coordinators/EmailCoordinator.swift
- ostelco-ios-client/ViewControllers/Email/CheckEmailViewController.swift
- ostelco-ios-client/ViewControllers/Email/EmailEntryViewController.swift
I made them use protocols rather than depend directly on the email
because we don't want to use this coordinator in the future.
> Refactor email coordinator controllers.

- dev-ostelco-ios-clientTests/CoordinatorTests/EdgeCasesInStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/NorwayUserHappyFlowWithJumioStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithScanICStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithSingPassStageDeciderTests.swift
- ostelco-core/Models/StageDecider.swift
Added comments about missing steps after walkthrough of current setup of StageDecider with product owner.
> Add comments about missing steps in StageDecider tests.

- ostelco-core/Network/PrimeAPI.swift
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/dev-ostelco-ios-client.xcscheme
- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
- ostelco-ios-client/ViewControllers/OhNoViewController.swift
I should not have comitted this. It's from when I was adding
localization support.
Also cleans up some issues we had from our last merges.
> Fix language display.

- ostelco-core/Network/PrimeAPI.swift
Current version of our app does not cache, so our GraphQL queries should model that behaviour by not caching any data.
> Dont cache context or simProfiles for region queries.

- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
Check if there is a simProfile in context before provisioning a new one when navigating to the EsimPendingDownloadViewController.
> Prevent duplicate provision of sim profiles.

- ostelco-core/Network/APIEndpoint.swift
- ostelco-core/Network/PrimeAPI.swift
- ostelco-ios-client/AppDelegate.swift
- ostelco-ios-client/Coordinators/EKYC/JumioCoordinator.swift
- ostelco-ios-client/Coordinators/EKYC/SingPassCoordinator.swift
- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
- ostelco-ios-client/ViewControllers/EKYC/MyInfoSummaryViewController.swift
I started by dumbing down the MyInfoSummaryViewController which was
still making API calls on its own. I found that the region we update was
hard-coded once we finish with that step which is not what we want. I
also found we were incorrectly ignoring dynamic links when a pending
email was not present even though the email did not matter by the time
we are handling a dynamic link. This
corrects the issues.
> Started refactoring and found a bug.

- ostelco-ios-client/ViewControllers/ReusableAlerts/NeedHelpActionSheet.swift
Show "Start Again" if user has a customer (you can't delete a customer if it doesn't exist in our servers)
Show "Log Out" if user has a firebase user.
> Enable need help actions based on user state.

- ostelco-core/ModelControllers/LocationController.swift
- ostelco-core/Models/Country.swift
- ostelco-core/Models/StageDecider.swift
- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
If you are outside of Singapore and want to sign up for Singapore, we
can't let you. We *can* let you sign up for anywhere else though, only
Singapore has this restriction.
> Only restrict users for Singapore.

- dev-ostelco-ios-clientTests/CoordinatorTests/EdgeCasesInStageDeciderTests.swift
- ostelco-core/ModelControllers/LocationController.swift
- ostelco-core/Models/OhNoIssueType.swift
- ostelco-core/Models/StageDecider.swift
- ostelco-core/Network/Headers.swift
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/dev-ostelco-ios-client.xcscheme
- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
- ostelco-ios-client/ModelControllers/UserManager.swift
- ostelco-ios-client/Storyboards/Base.lproj/Home.storyboard
- ostelco-ios-client/ViewControllers/Home/HomeViewController.swift
- ostelco-ios-client/ViewControllers/Login/LoginViewController.swift
- ostelco-ios-client/ViewControllers/OhNoViewController.swift
This adds support for showing the current country once you're done with onboarding.
This also fixes an issue where it would think you were done with on boarding because it didn't have the myinfo code anymore.
> Global Location Check: Showing country on Home view.

- ostelco-ios-client.xcodeproj/project.pbxproj
- ostelco-ios-client/Storyboards/Base.lproj/Address.storyboard
- ostelco-ios-client/Storyboards/Base.lproj/EKYC.storyboard
- ostelco-ios-client/Storyboards/Base.lproj/Home.storyboard
- ostelco-ios-client/Storyboards/Base.lproj/Settings.storyboard
- ostelco-ios-client/Storyboards/Base.lproj/SignUp.storyboard
- ostelco-ios-client/ViewControllers/ReusableAlerts/NeedHelpActionSheet.swift
Merge conflicts resulted in some issues with the display of addresses,
needed to correct it.
> Correct issues from merging.

- dev-ostelco-ios-clientTests/APITests/LiveAPITests.swift
- dev-ostelco-ios-clientTests/APITests/MockAPITests.swift
- dev-ostelco-ios-clientTests/MockJSON/context_jumio_approved.json
- dev-ostelco-ios-clientTests/MockJSON/context_jumio_rejected.json
- dev-ostelco-ios-clientTests/MockJSON/context_singapore_all_pending.json
- dev-ostelco-ios-clientTests/MockJSON/context_with_downloaded_sim_profile.json
- dev-ostelco-ios-clientTests/MockJSON/context_with_pending_sim_profile.json
- dev-ostelco-ios-clientTests/MockJSON/region_singapore.json
- dev-ostelco-ios-clientTests/MockJSON/regions.json
- dev-ostelco-ios-clientTests/MockJSON/regions_multiple.json
- dev-ostelco-ios-clientTests/MyInfoTests.swift
- ostelco-core/API.swift
- ostelco-core/Models/EKYCAddress.swift
- ostelco-core/Models/EKYCProfileUpdate.swift
- ostelco-core/Models/MyInfoDetails.swift
- ostelco-core/Models/Region.swift
- ostelco-core/Models/StageDecider.swift
- ostelco-core/context.graphql
- ostelco-core/schema.json
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/dev-ostelco-ios-client.xcscheme
- ostelco-ios-client/ModelControllers/AddressEditDataSource.swift
The server has renamed the ekyc status map value "ADDRESS_AND_PHONE" to
just "ADDRESS". Also we needed to remove some frields from myinfo that
we don't collect as they will likely be nil and cause myinfo loading to
fail.
> Update models for proper myinfo fields.

- dev-ostelco-ios-clientTests/CoordinatorTests/EdgeCasesInStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/NorwayUserHappyFlowWithJumioStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithScanICStageDeciderTests.swift
- dev-ostelco-ios-clientTests/CoordinatorTests/SingaporeUserHappyFlowWithSingPassStageDeciderTests.swift
- ostelco-core/ModelControllers/UserDefaultsWrapper.swift
- ostelco-core/Models/StageDecider.swift
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/OstelcoStyles.xcscheme
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/dev-ostelco-ios-client.xcscheme
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/ostelco-core.xcscheme
- ostelco-ios-client.xcodeproj/xcshareddata/xcschemes/ostelco-ios-client.xcscheme
- ostelco-ios-client/Coordinators/EKYC/SingPassCoordinator.swift
- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
This PR puts permission asking where it belongs based on our discussion and fixes the issue with the myinfo step not working.
> Rearrange steps

- ostelco-ios-client/Coordinators/OnboardingCoordinator.swift
A detail I forgot to note when moving everything around.
> We make sims for everyone, not just Singapore
